name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-linux-gnu
            os_name: linux
            arch: x86_64
          - target: aarch64-linux-gnu
            os_name: linux
            arch: aarch64
          - target: x86_64-macos-none
            os_name: macos
            arch: x86_64
          - target: aarch64-macos-none
            os_name: macos
            arch: aarch64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        
      - name: Build for ${{ matrix.target }}
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseSmall
          
      - name: Package binary
        run: |
          mkdir -p dist
          binary_name="rmate_launcher-${{ matrix.os_name }}-${{ matrix.arch }}"
          cp zig-out/bin/rmate_launcher "dist/${binary_name}"
          
          # Create tarball
          cd dist
          tar -czf "${binary_name}.tar.gz" "${binary_name}"
          
          # Generate checksum
          sha256sum "${binary_name}.tar.gz" > "${binary_name}.tar.gz.sha256"
          
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/rmate_launcher-${{ matrix.os_name }}-${{ matrix.arch }}.tar.gz
            dist/rmate_launcher-${{ matrix.os_name }}-${{ matrix.arch }}.tar.gz.sha256